name: GunDuels
version: '1.0-SNAPSHOT'
main: me.green.gunduels.GunDuels
author: Green
commands:
  heal:
    description: Heal command
    usage: /<command>
  givegun:
    description: Give gun command
    usage: /<command>
  joinduel:
    description: Join duel command
    usage: /<command>
  leaveduel:
    description: Leave duel command
    usage: /<command>