name: GunDuels
version: '1.0-SNAPSHOT'
main: me.green.gunduels.GunDuels
api-version: '1.18'
commands:
  testprojectile:
    description: Test projectile command
    usage: /<command>
  heal:
    description: Heal command
    usage: /<command>
  givegun:
    description: Give gun command
    usage: /<command>